---
title: "Investigating the Popularity of Scientific Phenomena on Social Media Platforms"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, cache=TRUE, 
                      fig.width=7, fig.height=3, fig.align = "center")
```

##Data input
Data are gathered from reddit using the Python Reddit API Wrapper (praw) in the file "reddit_api.py". The data are stored in "reddit_df.csv".
```{r}
#Read the reddit data into a dataframe
library(readr)
reddit_df <- read_csv("reddit_df.csv")
```

```{r}
#Wrangle the dates into a more readable format
require(lubridate)
require(dplyr)

#Store all of the POSIX dates into a vector
dates <- as.POSIXct(reddit_df$created_utc,origin = "1970-01-01",tz = "UTC")

#Use lubridate to read y,m,d,h from that vector
reddit_df <- reddit_df %>%  
  mutate(post_year = year(dates),post_month = month(dates), post_day = day(dates), post_hour = hour(dates))
```

```{r}
library(stringr)

#Filter by removing the Ask Me Anything (AMA) threads and the subreddit discussion
  #threads since these are not studies. 
reddit_df <- reddit_df %>%
  filter(!str_detect(subfield, " AMA")) %>%
  filter(subfield != "Subreddit Discussion") %>%
  filter(subfield != "Subreddit Feature")

#Display the remaining subfields
count(reddit_df,subfield)
```

```{r}
#Here is the dataframe in its current state:
head(reddit_df)
```

```{r}
#Create a new column for categorical time of day
#Time ranges: PST 6pm-3am night      3am-10am morning    11am-6pm day
mk_cat_time <- function(h)
{
  ifelse(h>18, "night", ifelse(h>10, "day", ifelse(h>2, "morning", "night")))
}

#Create a new column for categorical time of month
#Time ranges: 1-10 early  11-20 mid    21-31 late
mk_cat_day <- function(h)
{
  ifelse(h>20, "late", ifelse(h>10, "mid", "early"))
}

reddit_df <- reddit_df %>%
  mutate(cat_post_hour = mk_cat_time(post_hour)) %>%
  mutate(cat_post_day = mk_cat_day(post_day)) 
```

```{r}
#Turn all categorical variables into factors
reddit_df$author_flair_binary <- factor(reddit_df$author_flair_binary)
reddit_df$image <- factor(reddit_df$image)
reddit_df$journal_h_index <- factor(reddit_df$journal_h_index)
reddit_df$subfield <- factor(reddit_df$subfield)
#Uncomment year if analyzing more than 1 year, rf requires at least 2 levels per factor
#reddit_df$post_year <- factor(reddit_df$post_year)
reddit_df$post_month <- factor(reddit_df$post_month)
reddit_df$cat_post_hour <- factor(reddit_df$cat_post_hour)
reddit_df$cat_post_day <- factor(reddit_df$cat_post_day)

```

```{r}
require(ggplot2)
reddit_df %>%
  ggplot(aes(x=post_hour,y=log10(upvotes))) + geom_point() +
  ggtitle("Number of Upvotes by Post Time of Day") +
  xlab("Hour Posted (UTC)") + ylab("log(Number of Upvotes)") 
```

```{r}
high_h_index <- reddit_df %>% filter(journal_h_index=='high')
```

```{r}
hist(high_h_index$upvotes)
```

```{r}
reddit_df %>% group_by(image) %>% summarize(n())
```

```{r}
unique(reddit_df$author_flair)
```

```{r}
#To prepare for model building, we remove unnecessary columns:
reddit_df <- reddit_df %>%
  select(-X1,-title,-author,-author_created_date,-id,-created_utc,-domain,-url,-author_flair,-post_day,-post_hour)
```

```{r}
bef_rm <- nrow(reddit_df)

#Remove missing values
reddit_df <- reddit_df[complete.cases(reddit_df),]
aft_rm <- nrow(reddit_df)

paste("Proportion of rows removed: ",(bef_rm-aft_rm)/bef_rm)
```

```{r}
#Remove variables that are likely coupled with the response (provide plots)
reddit_df <- reddit_df %>%
  select(-num_comments,-gilded,-link_karma,-comment_karma)
```


```{r}
###Only run this chunk if we want categorical upvotes. If we cahnge back to regression, 
#We must change the response variables in the train functions in the chunks below

#Create a new column for categorical upvotes
#Ranges: 10000+ Very high     1000+ high     100+ moderate    0+ low
mk_cat_upvotes <- function(upv)
{
  ifelse(upv>10000, "Very High", ifelse(upv>1000, "High", ifelse(upv>100, "Moderate", "Low")))
}
reddit_df <- reddit_df %>%
  mutate(cat_upvotes = mk_cat_upvotes(upvotes)) %>%
  select(-upvotes)

reddit_df$cat_upvotes <- factor(reddit_df$cat_upvotes)
```

```{r}
#Packages required for trees
require(caret)
require(rpart)

#Set the seed for reproducibility
set.seed(47)

#Split the data into test and training
inTrain <- createDataPartition(y = reddit_df$cat_upvotes, p=0.80, list=FALSE)
reddit.train <- reddit_df[inTrain,]
reddit.test <- reddit_df[-c(inTrain),]
```

```{r}
#Build the random forest model
rf.reddit <- train(cat_upvotes ~., data=reddit.train, method="rf",
                      trControl = trainControl(method="oob"),
                      ntree=500, tuneGrid = data.frame(mtry=7),
                      importance = TRUE,na.action = na.exclude)
#

rf.reddit$finalModel
```

```{r}
varImp(rf.reddit$finalModel)
imp <- varImp(rf.reddit$finalModel)
data.frame(rownames(imp),imp$Overall) %>%
  arrange(desc(imp.Overall))
```

```{r}
require(rpart.plot)
#Build the random forest model
tr.reddit <- train(cat_upvotes ~., data=reddit.train, method="rpart2",
                      trControl = trainControl(method="none"),
                      tuneGrid= data.frame(maxdepth=10),)

tr.reddit$finalModel
rpart.plot(tr.reddit$finalModel)
```

